config/routes.rb
Rails.application.routes.draw do
  resources :ideas

  devise_for :users
  get 'book/index'

  resources :usuarios

  root :to => 'book#index' , :as => 'book'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
	validates :login, :senha, :foto, :nome, :cidade, :estado, :email, :descricao, :presence => true

	validates :login, :uniqueness => true
	validates :foto, :format => {
 		:with => %r{\.(gif|jpg|png)\z}i,
 		:message => 'A imagem deve estar em um dos formatos: GIF, JPG ou PNG.'
 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #def after_sign_in_path_for(resource)
  #  'http://localhost:3000/'
  #end
end

app/controllers/book_controller.rb
class BookController < ApplicationController
  def index  	
  	@usuarios = Usuario.order(:nome)
  end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usercrud = current_user
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
    @user = current_user
  end

  # GET /usuarios/new
  def new
    @usernew = current_user
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
    @useredit = current_user
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuário cadastrado com sucesso.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuário editado com sucesso.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuário excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
        @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:login, :senha, :foto, :nome, :cidade, :estado, :email, :descricao)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/book/index.html.erb
<% if notice %>
	<p id="notice"><%= notice %></p>
<% end %>

<div id="labelPerfil">
	<h1>Bem-Vindo!</h1>
	<p id="mensagem" >
		O novo "Yearbook It!" da disciplina de Tópicos Especiais da Computação acaba de chegar. Cadastre-se já e compartilhe com seus amigos .
	</p>
</div>

<% @usuarios.each do |usuario| %>
	<div class="entry">
		<%= link_to "http://localhost:3000/usuarios/"+usuario.id.to_s do %>
			<%= image_tag(usuario.foto) %>
		<% end %>
		<h3><%= usuario.nome %></h3>
		<%= sanitize usuario.descricao %>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Yearbook It!</title>	
	<%= stylesheet_link_tag "scaffold" %>
	<%= stylesheet_link_tag "topicos" , :media => "all" %>
	<%= javascript_include_tag :defaults %>
	<%= csrf_meta_tag %>
</head>

<body id="store">
	<div class="cmpLogar">
		<p class="logar">
        <% if user_signed_in? %>
          Logado como <strong><%= current_user.email %></strong>.
          <%= link_to 'Configurações da Conta', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Sair", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Registrar", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Logar", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
        </p>
	</div>

	<div id="banner">
		<%= image_tag("logo2.gif") %>
		<%= @page_title || "" %>
	</div>

	<div id="menu">
		<a id="cmpMenu" href="http://localhost:3000">Home</a>
		<a id="cmpMenu" href="http://localhost:3000/usuarios">Usuários</a>		
	</div>

	<div id="columns">
		<div id="main">
			<%= yield %>
		</div>
	</div>
</body>

</html>

app/views/usuarios/_form.html.erb
<%  if current_user != nil %> 
    <%= form_for(@usuario) do |f| %>
      <% if @usuario.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@usuario.errors.count, "error") %> impediram o cadastro do usuário:</h2>

          <ul>
          <% @usuario.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :login %><br>
        <%= f.text_field :login, :placeholder => 'Email válido' %>
      </div>
      <div class="field">
        <%= f.label :senha %><br>
        <%= f.password_field :senha, :placeholder => '8 dígitos' %>
      </div>
      <div class="field">
        <%= f.label :foto %><br>
        <%= f.text_field :foto, :placeholder => 'Url da imagem' %>
      </div>
      <div class="field">
        <%= f.label :nome %><br>
        <%= f.text_field :nome, :placeholder => 'Nome completo' %>
      </div>
      <div class="field">
        <%= f.label :cidade %><br>
        <%= f.text_field :cidade, :placeholder => 'Cidade onde mora'  %>
      </div>
      <div class="field">
        <%= f.label :estado %><br>
        <%= f.text_field :estado, :placeholder => 'Estado onde mora'  %>
      </div>
      <div class="field">
        <%= f.label :email %><br>
        <%= f.text_field :email, :placeholder => 'Email válido'  %>
      </div>
      <div class="field">
        <%= f.label :descricao %><br>
        <%= f.text_area :descricao, :rows => 5, :placeholder => 'Uma breve descrição sobre você'  %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
<% else %>
  <script type="text/javascript">
    window.location.href="http://localhost:3000/users/sign_in" 
  </script>
<% end %>

app/views/usuarios/edit.html.erb
<%  if @useredit != nil %>  
  <div id="labelPerfil">
    <p>
      <h1>Editar</h1>
    </p>
  </div>

  <fieldset id="fundoform">    
	 <%= render 'form' %>
  </fieldset>

  <div id="botaoc">    
  	<%= link_to 'Exibir', @usuario %> |
  	<%= link_to 'Voltar', usuarios_path %>
  </div>
<% else %>
  <script type="text/javascript">
    window.location.href="http://localhost:3000/users/sign_in" 
  </script>
<% end %>

app/views/usuarios/index.html.erb
    <%  if @usercrud != nil %> 
<div id="usuario_list">
      <div id="labelPerfil">
        <h1>Usuários</h1>
      </div>
    <table>
      <% @usuarios.each do |usuario| %>
     <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
      <td>
        <%= image_tag(usuario.foto, :class => 'list_image') %>
      </td>
      <td class="list_description">
        <dl>
          <dt><%= usuario.nome %></dt>
          <dd><%= usuario.cidade %></dd>
          <dd><%= usuario.estado %></dd>
          <dd><%= usuario.email %></dd>
          <dd><%= truncate(strip_tags(usuario.descricao),:length => 100)%></dd>
        </dl>
      </td>
      <td class="list_actions">
        <div id="botaoa">
          <%= link_to 'Exibir', usuario %>
        </div>
        <div id="botaob">      
          <%= link_to 'Editar', edit_usuario_path(usuario) %>
        </div>
        <div id="botaoa">
          <%= link_to 'Excluir', usuario, :confirm => 'Deseja realmente excluir usuário?', :method => :delete %>          
        </div>
      </td>
    </tr>
    <% end %>
    </table>
    </div>
    <br />
    <div id="botaoc">      
      <%= link_to 'Novo usuário', new_usuario_path %>
    </div>
<% else %>
  <script type="text/javascript">
    window.location.href="http://localhost:3000/users/sign_in" 
  </script>
<% end %>    

app/views/usuarios/new.html.erb
<%  if @usernew != nil %> 
	<div id="labelPerfil">
		<h1>Cadastrar</h1>
	</div>	

  <fieldset id="fundoform">    
	 <%= render 'form' %>
  </fieldset>

  <div id="botaoc">  	
	<%= link_to 'Voltar', usuarios_path %>
  </div>
<% else %>
  <script type="text/javascript">
    window.location.href="http://localhost:3000/users/sign_in" 
  </script>
<% end %>

app/views/usuarios/show.html.erb
<%  if @user != nil %>  

  <div id="labelPerfil">
    <p>
      <h1>Perfil</h1>
    </p>
  </div>

  <div id="fundo">
    <table>
      <tr>
        <th></th>
        <th></th>
      </tr>
      <tr>
        <td><%= image_tag(@usuario.foto, :class => 'list_image') %></td>
        <td>
          <table>  
            <tr>
              <th id="cedula_A">Nome completo: </th>
              <td><%= @usuario.nome %></td>
            </tr>
            <tr>
              <th id="cedula_B">Cidade: </th>
              <td><%= @usuario.cidade %></td>
            </tr>
            <tr>            
              <th id="cedula_A">Estado: </th>
              <td><%= @usuario.estado %></td>
            </tr>
            <tr>            
              <th id="cedula_B">Email: </th>
              <td><%= @usuario.email %></td>
            </tr>
            <tr>            
              <th id="cedula_A">Descrição: </th>
              <td><%= @usuario.descricao %></td>
            </tr>
          </table>        
        </td>
      </tr>
    </table>
  </div>

  <div id="botaoc">    
    <%= link_to 'Editar', edit_usuario_path(@usuario) %> |
    <%= link_to 'Voltar', usuarios_path %>
  </div>
  <% else %>
    <script type="text/javascript">
       window.location.href="http://localhost:3000/users/sign_in" 
    </script>
<% end %>